openapi: 3.0.0
info:
  description: Api Documentation
  version: 0.1.0
  title: Api Documentation
  termsOfService: urn:tos
  contact: { }
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0

paths:
  /api/compare:
    post:
      tags:
        - Schema Compatibility
      summary: compareSchemas
      operationId: compareSchemas
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SchemaCompatibilitySubject'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SchemaCompatibilityResponse'

components:
  schemas:
    SchemaType:
      type: string
      enum:
        - AVRO
        - JSON
        - PROTOBUF

    CompatibilityLevel:
      type: string
      enum:
        - BACKWARD
        - FORWARD
        - FULL
        - NONE

    SchemaCompatibilitySubject:
      type: object
      properties:
        schemaType:
          $ref: '#/components/schemas/SchemaType'
        compatibilityLevel:
          $ref: '#/components/schemas/CompatibilityLevel'
        existingSchema:
          type: string
        proposedSchema:
          type: string
      required:
        - schemaType
        - compatibilityLevel
        - existingSchema
        - proposedSchema

    SchemaCompatibilityResponse:
      type: object
      properties:
        isCompatible:
          type: boolean
        message:
          type: string
      required:
        - isCompatible
        - message
