.PHONY: build-docker help

build-docker:
	@echo "Building Docker image..."
	docker buildx build -t spring-boot-docker .

help:
	@echo "Usage: make [target]"
	@echo ""
	@echo "Targets:"
	@echo "  build-docker      		Build the Docker image"
